service: aws-step-func

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

# environment:
#   GET_USER_FLOW_ARN: ${self:resources.Outputs.GetUserFlowOutout.Value}

functions:
  getUserEndpoint:
    environment: 
      GET_USER_FLOW_ARN: ${self:resources.Outputs.GetUserFlowOutout.Value}
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
  getUser:
    handler: handlers/user.get

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-step-functions

custom:
  serverless-offline:
    port: 3000

stepFunctions:
  stateMachines:
    GetUserFlowMachine:
      name: getUserFlow
      definition:
        StartAt: getUser
        States: 
          getUser: 
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getUser
            End: true

resources:
  Outputs:
    GetUserFlowOutout:
      Description: The ARN of the getUserFlow machine
      Value:
        Ref: GetUserFlow
      Export:
        Name: GetUserFlowMachine
